name: Build and Deploy React App to CloudFront
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: test-front-sirius
      DIST: build
      REGION: eu-central-1
      DIST_ID: E28EGYBFYFZFXB

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
    
    - name: Install Dependencies
      run: |
        node --version
        npm ci --production
    
    - name: Build Static Website
      run: CI=false npm run build

    
    - name: Copy files to the production website with AWS CLI
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}
    
    - name: Copy files to the production website with AWS CLI
      run: |
        aws cloudfront create-invalidation \
        --distribution-id ${{ env.DIST_ID }} \
        --paths "/*"